environment:
  matrix:
    - PYTHON_VERSION: "3.9"
    - PYTHON_VERSION: "3.10"

install:
  - ps: Install-Python '%PYTHON_VERSION%' x64
  - ps: $env:Path = "$env:Path;C:\Python%PYTHON_VERSION%\Scripts"
  - pip install -r requirements.txt
